apiVersion: v1
kind: Service
metadata:
  name: express-backend-service
spec:
  selector:
    app: express-backend  # Ensure the service selects the correct pods
  ports:
    - protocol: TCP
      port: 5000     # The port the service exposes
      targetPort: 5000 # The container's port (matches containerPort from Deployment)
  type: ClusterIP  # Default type, exposing the service inside the cluster
