apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1  # Number of replicas (pods) for frontend
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: poolfresz/react-app:latest
          ports:
            - containerPort: 5173  # The port the container will expose (typically 80 for a React app)
