name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4    # Updated from v3 to v4 for Node.js 20 support
        
      - name: Run Super-Linter
        uses: github/super-linter@v5  # v5 is already Node.js 20 compatible
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          VALIDATE_CSS: false
          VALIDATE_ENV: false
          VALIDATE_MARKDOWN: false
          VALIDATE_YAML: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_GITLEAKS: false
